on:
  check_suite:
    types: [rerequested,completed]
  check_run:
    types: [rerequested,completed]

jobs:
  apply_label_merged:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['automerge']
            })
